// Code generated by protoc-gen-go.
// source: basic_protocol.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	basic_protocol.proto

It has these top-level messages:
	BasicOps
	BasicResp
*/
package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type BasicOps struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BasicOps) Reset()         { *m = BasicOps{} }
func (m *BasicOps) String() string { return proto.CompactTextString(m) }
func (*BasicOps) ProtoMessage()    {}

func (m *BasicOps) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *BasicOps) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type BasicResp struct {
	ResponseCode     *int32 `protobuf:"varint,1,req,name=response_code" json:"response_code,omitempty"`
	Value            []byte `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	Key              []byte `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *BasicResp) Reset()         { *m = BasicResp{} }
func (m *BasicResp) String() string { return proto.CompactTextString(m) }
func (*BasicResp) ProtoMessage()    {}

func (m *BasicResp) GetResponseCode() int32 {
	if m != nil && m.ResponseCode != nil {
		return *m.ResponseCode
	}
	return 0
}

func (m *BasicResp) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *BasicResp) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func init() {
}
